- name: Wait for InfluxDB to startup completely
  wait_for:
    host: "localhost"
    port: 8086
    timeout: 10

- name: Get influxdb datasource
  uri:
    url: "https://localhost/api/datasources/id/WSP"
    method: GET
    user: "{{ grafana_username }}"
    password: "{{ grafana_password }}"
    force_basic_auth: yes
    status_code: 404,200
    validate_certs: no
    headers:
      Accept: "application/json"
  register: resp

- name: Define influxdb datasource
  uri:
    url: "https://localhost/api/datasources"
    method: POST
    user: "{{ grafana_username }}"
    password: "{{ grafana_password }}"
    body: "{{ lookup('file', 'datastore.json') | from_json }}"
    validate_certs: no
    status_code: 200
    body_format: json
    force_basic_auth: yes
    headers:
      Content-Type: "application/json"
  when: resp.status == 404
